#! /bin/bash -xe

# Wait for all interfaces to get added.
# By default only check for WAN and AUX interfaces
# Any other interface needs to be passed via ENV to be checked.
# Mandatory checks
while [ -z $(ls /sys/class/net | grep -w eth1) ]; do
    echo "WAN interface not found"
    sleep 5
done
ip link set eth1 up

while [ -z $(ls /sys/class/net | grep -w aux0) ]; do
    echo "WAN interface not found"
    sleep 5
done
ip link set aux0 up

# Zebra Configuration
ZEBRA_CONF=`cat <<EOF
!
! Interface #IFACE
!
interface #IFACE
 ip address #IP4
 ipv6 address #IP6
 no ipv6 nd suppress-ra
 ipv6 nd router-preference high
 no ipv6 nd managed-config-flag
 no ipv6 nd other-config-flag
!
EOF
`

# PIMD Configuration
PIMD_CONF=`cat <<EOF

interface #IFACE
 ip pim ssm
 ip igmp

EOF
`

# RIPD Conf
RIPD_CONF=`cat <<EOF
interface #IFACE
    ip rip authentication mode md5
    ip rip authentication key-chain mykey1

EOF
`

# Checks and configurations for CPE interfaces
for i in $CPE_MGMT $CPE_DATA $CPE_VOICE;
do
    IFS=,
    read IFACE IP4 IP6 <<<$i

    while [ -z $(ls /sys/class/net | grep -w $IFACE) ]
    do
        echo "$IFACE interface not found"
        sleep 5
    done
    ip link set $IFACE up

    # Update Zebra Conf
    echo "$ZEBRA_CONF" | sed "s|#IFACE|$IFACE|" | \
    sed "s|#IP4|$IP4|" | sed "s|#IP6|$IP6|" >> /etc/frr/zebra.conf

    # Update PIM Conf
    echo "$PIMD_CONF" | sed "s|#IFACE|$IFACE|" >> /etc/frr/pimd.conf

    # Update RIP Conf
    RIPD_TMP=$(sed "s|! Add active RIP network|    network $IFACE\n! Add active RIP network|"  /etc/frr/ripd.conf)
    echo $RIPD_TMP > /etc/frr/ripd.conf
    echo "$RIPD_CONF" | sed "s|#IFACE|$IFACE|" >> /etc/frr/ripd.conf

done

unset IFS
sysctl -p /etc/sysctl.conf

# Modify SMCroute to redirect at $MCAST_TARGET iface
sed -i "s|#TARGET|$MCAST_TARGET|" /etc/smcroute.conf

# Zebra is loaded by default
sed -i "/zebra_options=/d" /etc/frr/daemons
echo "zebra_options=\"  -A 127.0.0.1 -s 90000000 -f /etc/frr/zebra.conf\"" >> /etc/frr/daemons


echo "Starting daemons."
for svc in bgpd isisd ospfd ospf6d ripd ripngd pimd pim6d; do
    if [ -f /etc/frr/${svc}.conf ]; then
        echo "Starting ${svc}."
        sed -i s"/${svc}=no/${svc}=yes/" /etc/frr/daemons
        sed -i "/${svc}_options=/d" /etc/frr/daemons
        if [[ ${svc} == *"6"* ]]; then
            # IPv6 service
            echo "${svc}_options=\"  -A ::1 -f /etc/frr/${svc}.conf\"" >> /etc/frr/daemons
        else
            echo "${svc}_options=\"  -A 127.0.0.1 -f /etc/frr/${svc}.conf\"" >> /etc/frr/daemons
        fi
    fi
done

# New changes in FRR 9.0+
if [ -f /etc/frr/staticd.conf ]; then
    echo "staticd=yes" >> /etc/frr/daemons
fi

service frr start
sleep 5

update-alternatives --set iptables /usr/sbin/iptables-legacy
update-alternatives --set ip6tables /usr/sbin/ip6tables-nft
iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE

# Start DHCP relay once all interfaces are up with FRR
if [ ! -z $(echo $DHCP_RELAY) ]; then
    for i in $CPE_MGMT $CPE_DATA $CPE_VOICE;
    do
        IFS=,
        read RELAY4 RELAY6 <<<$DHCP_RELAY
        read IFACE IP4 IP6 <<<$i
        dhcrelay -4 -a -iu eth1 -id $IFACE $RELAY4
        dhcrelay -6 -I -l $IFACE -u $RELAY6%eth1
    done
    unset IFS
fi

service smcroute start

# Run sshd by default
/usr/sbin/sshd -D
