#!/bin/bash
if [ "$LEGACY" == "no" ]; then
    isolate_docker_iface
fi

count=$((TIMEOUT/5))
for _i in $(seq 1 $count); do
    if ! find /sys/class/net | grep -q -w eth1 ; then
        echo "eth1 interface not found"
        sleep 5
        continue
    fi
    break
done

# Loading default conf values assuming interface eth1 will be brought up
cat > /etc/dnsmasq.conf << EOF
local-ttl=60
no-resolv
no-hosts
local=/boardfarm.com/
server=$DNS_UPSTREAM
interface=eth1
addn-hosts=/etc/dnsmasq.hosts
EOF

DNSMASQ_HOSTS=$(cat << EOF
4003:1::1 aftr.boardfarm.com
172.25.1.101 wan.boardfarm.com
2001:dead:beef:2::101 wan.boardfarm.com
2001:dead:beef:2::40 acs_server.boardfarm.com
172.25.1.40 acs_server.boardfarm.com
172.25.1.101 ipv4wan.boardfarm.com
2001:dead:beef:2::101 ipv6wan.boardfarm.com
2001:dead:beef:2::101 ipv6.google.com
172.25.1.101 www.google.com
EOF
)

cat > /etc/danted.conf << EOF
logoutput: stderr
internal: 0.0.0.0 port = 8080
external: eth1
clientmethod: none
socksmethod: username none #rfc931
user.privileged: root
user.unprivileged: nobody
user.libwrap: nobody
client pass {
    from: 0.0.0.0/0 to: 0.0.0.0/0
    log: connect disconnect error
}
socks pass {
    from: 0.0.0.0/0 to: 0.0.0.0/0
    log: connect disconnect error
}
EOF

# Loading default host values based on DHCP configuration
if [ ! -f /etc/dnsmasq.hosts ]; then
    cat > /etc/dnsmasq.hosts <<< "$DNSMASQ_HOSTS"
fi

service tftpd-hpa start;
service lighttpd start;
service dnsmasq start;
service danted start
/usr/sbin/sshd -D
