#!/usr/bin/env python3

import os, sys, json

#getpp show WAN_MAC_ADDRESS


def main():

    config = {
        "WAN_MAC_ADDRESS" : "e4c0e245245f",
        "MANUFACTURER_OUI" : "38A659",
        "SERIAL_NUMBER" : "YAAD1256A042",
        "C_PRODUCT_ID" : "MERCV3",
        "S_PRODUCT_ID" : "Fast5685-LG"
    }

    fn = '/var/tmp/getpp.json'

    if os.path.isfile(fn):
        with open(fn, 'r') as fp:
            config = json.loads(fp.read())

    if len(sys.argv) == 1:
        print("no arguments..")
        print(config)

    elif sys.argv[1] == 'show':
        print(config[sys.argv[2]])

    with open(fn, 'w+') as fp:
        fp.write(json.dumps(config))


if __name__ == '__main__':
    main()
