#!/bin/sh

aftr_start()
{
    ip link set tun0 up
    sysctl -w net.ipv4.ip_forward=1
    sysctl -w net.ipv6.conf.all.forwarding=1
    sysctl -w net.ipv6.conf.all.disable_ipv6=0
    ip addr add 192.0.0.1 peer 192.0.0.2 dev tun0
    ip route add 198.18.0.0/16 dev tun0
    ip -6 route add
    iptables -t nat -F
    iptables -t nat -A POSTROUTING -s 198.18.200.111 -j SNAT --to-source $PUBLIC
    iptables -t nat -A PREROUTING -p tcp -d $PUBLIC --dport 60000:64999 -j DNAT --to-destination 198.18.200.111
    iptables -t nat -A PREROUTING -p udp -d $PUBLIC --dport 60000:64999 -j DNAT --to-destination 198.18.200.111
    iptables -t nat -A OUTPUT -p tcp -d $PUBLIC --dport 60000:64999 -j DNAT --to-destination 198.18.200.111
    iptables -t nat -A OUTPUT -p udp -d $PUBLIC --dport 60000:64999 -j DNAT --to-destination 198.18.200.111
}
aftr_stop()
{
    iptables -t nat -F
    ip link set tun0 down
}
set -x
PUBLIC=`ip addr show dev eth1 | grep -w inet | awk '{print $2}' | awk -F/ '{print $1}'`

case "$1" in
start)
    aftr_start
    ;;
stop)
    aftr_stop
    ;;
*)
    echo "Usage: $0 start|stop"
    exit 1
    ;;
esac

exit 0