#!/bin/bash -xe

if [ "$LEGACY" == "no" ]; then
    isolate_docker_iface
fi

sed -i s'|#precedence ::ffff:0:0\/96  100|precedence ::ffff:0:0\/96  100|' /etc/gai.conf
sed -i -E 's/disable.+= yes/disable         = no/' /etc/xinetd.d/time
sed -i '/INTERNAL/a \        flags           = IPv6' /etc/xinetd.d/time

if [ -n "$NTP_UPSTREAM" ]; then
    echo "server $NTP_UPSTREAM iburst" >> /etc/ntpsec/ntp.conf
fi

service xinetd start
service ntpsec start
/usr/sbin/sshd -D
